# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Polish zloty', max_digits=6)),
                ('preparation_time', models.IntegerField(blank=True, help_text='Time in minutes needed to prepare a meal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vegan', models.NullBooleanField()),
                ('cards', models.ManyToManyField(to='menu.Card')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
