# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cards',
            field=models.ManyToManyField(blank=True, to='menu.Card'),
        ),
    ]
