# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180902_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='menu.Dish'),
        ),
    ]
