# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180902_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='cards', to='menu.Dish'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='preparation_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Time in minutes needed to prepare a meal', null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in Polish zloty', max_digits=6, null=True),
        ),
    ]
