# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180902_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['id'], 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AddField(
            model_name='card',
            name='dishes_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
